services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p static/uploads
    startCommand: |
      if [ -n "$DATABASE_URL" ]; then
        echo "Using PostgreSQL database"
      else
        echo "Using SQLite database"
      fi
      gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: GITHUB_OAUTH_CLIENT_ID
        sync: false
      - key: GITHUB_OAUTH_CLIENT_SECRET
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "False"
      - key: SQLALCHEMY_ENGINE_OPTIONS
        value: '{"pool_size": 5, "max_overflow": 10, "pool_timeout": 30, "pool_pre_ping": true}'

databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio